import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// App-owned localization for visible product copy.
///
/// Chinese source copy is used as the stable lookup key so existing screens can
/// be migrated without coupling product text to widget structure. New copy
/// should be added to [_catalog] before it is shipped.
class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations) ??
      const AppLocalizations(Locale('zh', 'CN'));

  static const delegate = _AppLocalizationsDelegate();

  String text(String source) {
    if (source.isEmpty ||
        locale.languageCode == 'zh' && locale.countryCode != 'HK') {
      return source;
    }

    final translated = _catalog[source]?[_languageIndex(locale)];
    if (translated != null && translated.isNotEmpty) return translated;

    return _translatePattern(source, locale);
  }
}

extension AppLocalizationContext on BuildContext {
  String tr(String source) => AppLocalizations.of(this).text(source);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      const {'zh', 'en'}.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// zh-HK, en, ja, ko, vi, ru, es, fr, de, pt-BR, tr
int _languageIndex(Locale locale) {
  if (locale.languageCode == 'zh') return 0;
  return const {
        'en': 1,
        'ja': 2,
        'ko': 3,
        'vi': 4,
        'ru': 5,
        'es': 6,
        'fr': 7,
        'de': 8,
        'pt': 9,
        'tr': 10,
      }[locale.languageCode] ??
      1;
}

const _catalog = <String, List<String>>{
  '全球账户': [
    '全球帳戶',
    'Global Accounts',
    'グローバル口座',
    '글로벌 계좌',
    'Tài khoản toàn cầu',
    'Глобальные счета',
    'Cuentas globales',
    'Comptes internationaux',
    'Globale Konten',
    'Contas globais',
    'Küresel hesaplar',
  ],
  '暂无全球账户': [
    '暫無全球帳戶',
    'No global accounts yet',
    'グローバル口座はまだありません',
    '아직 글로벌 계좌가 없습니다',
    'Chưa có tài khoản toàn cầu',
    'Глобальных счетов пока нет',
    'Aún no hay cuentas globales',
    'Aucun compte international pour le moment',
    'Noch keine globalen Konten',
    'Ainda não há contas globais',
    'Henüz küresel hesap yok',
  ],
  '全球账户资料发布后，这里会展示最新内容。': [
    '全球帳戶資料發布後，這裡會顯示最新內容。',
    'The latest global account guides will appear here.',
    'グローバル口座の最新情報がここに表示されます。',
    '최신 글로벌 계좌 안내가 여기에 표시됩니다.',
    'Thông tin tài khoản toàn cầu mới nhất sẽ xuất hiện tại đây.',
    'Здесь появятся актуальные материалы о глобальных счетах.',
    'Aquí aparecerán las últimas guías de cuentas globales.',
    'Les dernières informations sur les comptes internationaux apparaîtront ici.',
    'Aktuelle Informationen zu globalen Konten erscheinen hier.',
    'As informações mais recentes sobre contas globais aparecerão aqui.',
    'En güncel küresel hesap bilgileri burada görünecek.',
  ],
  '卡友榜': [
    '卡友榜',
    'Community',
    'コミュニティ',
    '카드 사용자',
    'Cộng đồng',
    'Сообщество',
    'Comunidad',
    'Communauté',
    'Community',
    'Comunidade',
    'Topluluk',
  ],
  '稳定币': [
    '穩定幣',
    'Stablecoins',
    'ステーブルコイン',
    '스테이블코인',
    'Stablecoin',
    'Стейблкоины',
    'Stablecoins',
    'Stablecoins',
    'Stablecoins',
    'Stablecoins',
    'Stablecoinler',
  ],
  '卡友贡献活跃榜': [
    '卡友貢獻活躍榜',
    'Community Contribution Ranking',
    'コミュニティ貢献ランキング',
    '커뮤니티 기여 순위',
    'Xếp hạng đóng góp cộng đồng',
    'Рейтинг вклада сообщества',
    'Ranking de contribución',
    'Classement des contributions',
    'Community-Beitragsranking',
    'Ranking de contribuição',
    'Topluluk katkı sıralaması',
  ],
  '本月活跃': [
    '本月活躍',
    'Active This Month',
    '今月のアクティブ',
    '이번 달 활동',
    'Hoạt động tháng này',
    'Активность за месяц',
    'Actividad mensual',
    'Activité du mois',
    'Diesen Monat aktiv',
    'Atividade mensal',
    'Bu ay aktif',
  ],
  '贡献总榜': [
    '貢獻總榜',
    'All-time Contribution',
    '累計貢献',
    '누적 기여',
    'Đóng góp tổng',
    'Общий вклад',
    'Contribución total',
    'Contribution totale',
    'Gesamtbeitrag',
    'Contribuição total',
    'Toplam katkı',
  ],
  '会员身份不参与计分': [
    '會員身分不參與計分',
    'Membership does not affect scores',
    '会員資格はスコアに影響しません',
    '멤버십은 점수에 영향을 주지 않습니다',
    'Thành viên không ảnh hưởng điểm số',
    'Подписка не влияет на баллы',
    'La membresía no afecta la puntuación',
    'L’abonnement n’affecte pas le score',
    'Mitgliedschaft beeinflusst die Wertung nicht',
    'A assinatura não afeta a pontuação',
    'Üyelik puanı etkilemez',
  ],
  '仅供资料浏览 · 不加入本机卡包': [
    '僅供資料瀏覽 · 不加入本機卡包',
    'Information only · Not added to your card wallet',
    '情報閲覧のみ・カードウォレットには追加されません',
    '정보 전용 · 카드 지갑에 추가되지 않음',
    'Chỉ để tham khảo · Không thêm vào ví thẻ',
    'Только информация · Не добавляется в кошелёк',
    'Solo información · No se añade a la cartera',
    'Informations uniquement · Non ajouté au portefeuille',
    'Nur zur Information · Wird nicht zur Kartenmappe hinzugefügt',
    'Apenas informativo · Não é adicionado à carteira',
    'Yalnızca bilgi · Kart cüzdanına eklenmez',
  ],
  '多币种持有 · 收款 · 换汇': [
    '多幣種持有 · 收款 · 換匯',
    'Hold · Receive · Convert multiple currencies',
    '複数通貨の保有・受取・両替',
    '다중 통화 보유 · 수취 · 환전',
    'Giữ · Nhận · Chuyển đổi nhiều loại tiền',
    'Хранение · Получение · Обмен валют',
    'Mantén · Recibe · Convierte divisas',
    'Détenir · Recevoir · Convertir des devises',
    'Halten · Empfangen · Währungen tauschen',
    'Manter · Receber · Converter moedas',
    'Çoklu para birimi tut · Al · Dönüştür',
  ],
  '中国大陆申请与 KYC': [
    '中國大陸申請與 KYC',
    'Mainland China Application & KYC',
    '中国本土からの申請とKYC',
    '중국 본토 신청 및 KYC',
    'Đăng ký và KYC tại Trung Quốc đại lục',
    'Заявка и KYC в материковом Китае',
    'Solicitud y KYC en China continental',
    'Demande et KYC en Chine continentale',
    'Antrag und KYC in Festlandchina',
    'Solicitação e KYC na China continental',
    'Çin ana karası başvurusu ve KYC',
  ],
  '主流 U 卡链上数据': [
    '主流 U 卡鏈上數據',
    'Mainstream U Card On-chain Data',
    '主要Uカードのオンチェーンデータ',
    '주요 U카드 온체인 데이터',
    'Dữ liệu on-chain thẻ U',
    'Ончейн-данные U-карт',
    'Datos on-chain de tarjetas U',
    'Données on-chain des cartes U',
    'On-Chain-Daten führender U-Karten',
    'Dados on-chain de cartões U',
    'U Kart zincir üstü verileri',
  ],
  '查看详情': [
    '查看詳情',
    'View Details',
    '詳細を見る',
    '상세 보기',
    'Xem chi tiết',
    'Подробнее',
    'Ver detalles',
    'Voir les détails',
    'Details ansehen',
    'Ver detalhes',
    'Ayrıntıları gör',
  ],
  '资产': [
    '資產',
    'Assets',
    '資産',
    '자산',
    'Tài sản',
    'Активы',
    'Activos',
    'Actifs',
    'Assets',
    'Ativos',
    'Varlıklar',
  ],
  '市值': [
    '市值',
    'Market Cap',
    '時価総額',
    '시가총액',
    'Vốn hóa',
    'Капитализация',
    'Capitalización',
    'Capitalisation',
    'Marktkapitalisierung',
    'Capitalização',
    'Piyasa değeri',
  ],
  '网络': [
    '網路',
    'Network',
    'ネットワーク',
    '네트워크',
    'Mạng',
    'Сеть',
    'Red',
    'Réseau',
    'Netzwerk',
    'Rede',
    'Ağ',
  ],
  '预览': [
    '預覽',
    'Preview',
    'プレビュー',
    '미리보기',
    'Xem trước',
    'Предпросмотр',
    'Vista previa',
    'Aperçu',
    'Vorschau',
    'Prévia',
    'Önizleme',
  ],
  '集卡': [
    '集卡',
    'Card Hub',
    'カードハブ',
    '카드 허브',
    'Card Hub',
    'Картотека',
    'Card Hub',
    'Card Hub',
    'Card Hub',
    'Card Hub',
    'Card Hub',
  ],
  '我的卡片': [
    '我的卡片',
    'My Cards',
    'マイカード',
    '내 카드',
    'Thẻ của tôi',
    'Мои карты',
    'Mis tarjetas',
    'Mes cartes',
    'Meine Karten',
    'Meus cartões',
    'Kartlarım',
  ],
  '市场': [
    '市場',
    'Market',
    'マーケット',
    '마켓',
    'Thị trường',
    'Рынок',
    'Mercado',
    'Marché',
    'Markt',
    'Mercado',
    'Pazar',
  ],
  '卡包': [
    '卡包',
    'Card Wallet',
    'カードウォレット',
    '카드 지갑',
    'Ví thẻ',
    'Кошелёк карт',
    'Cartera de tarjetas',
    'Portefeuille de cartes',
    'Kartenmappe',
    'Carteira de cartões',
    'Kart cüzdanı',
  ],
  '隐藏或显示底部导航栏': [
    '隱藏或顯示底部導覽列',
    'Hide or show bottom navigation',
    '下部ナビゲーションを表示／非表示',
    '하단 탐색 모음 표시 또는 숨기기',
    'Ẩn hoặc hiện thanh điều hướng dưới cùng',
    'Показать или скрыть нижнюю навигацию',
    'Ocultar o mostrar la navegación inferior',
    'Afficher ou masquer la navigation inférieure',
    'Untere Navigation ein- oder ausblenden',
    'Mostrar ou ocultar a navegação inferior',
    'Alt gezinmeyi göster veya gizle',
  ],
  '探索市面上热门的卡片': [
    '探索市面上熱門的卡片',
    'Explore popular cards on the market',
    '市場で人気のカードを探す',
    '시장에서 인기 있는 카드를 둘러보세요',
    'Khám phá các thẻ phổ biến trên thị trường',
    'Изучайте популярные карты на рынке',
    'Explora tarjetas populares del mercado',
    'Découvrez les cartes populaires du marché',
    'Entdecke beliebte Karten auf dem Markt',
    'Explore cartões populares no mercado',
    'Piyasadaki popüler kartları keşfedin',
  ],
  'U卡': [
    'U卡',
    'U Cards',
    'Uカード',
    'U카드',
    'Thẻ U',
    'U-карты',
    'Tarjetas U',
    'Cartes U',
    'U-Karten',
    'Cartões U',
    'U Kartlar',
  ],
  '身份证可开': [
    '身分證可開',
    'ID accepted',
    '身分証で申請可',
    '신분증으로 신청 가능',
    'Dùng được CCCD',
    'Можно с удостоверением',
    'Con documento de identidad',
    'Pièce d’identité acceptée',
    'Mit Ausweis möglich',
    'Aceita documento de identidade',
    'Kimlikle başvuru mümkün',
  ],
  '护照可开': [
    '護照可開',
    'Passport accepted',
    'パスポートで申請可',
    '여권으로 신청 가능',
    'Dùng được hộ chiếu',
    'Можно с паспортом',
    'Con pasaporte',
    'Passeport accepté',
    'Mit Reisepass möglich',
    'Aceita passaporte',
    'Pasaportla başvuru mümkün',
  ],
  '热门榜': [
    '熱門榜',
    'Popular',
    '人気ランキング',
    '인기 랭킹',
    'Xếp hạng phổ biến',
    'Популярное',
    'Populares',
    'Populaires',
    'Beliebt',
    'Em alta',
    'Popüler',
  ],
  '稳定币数据': [
    '穩定幣數據',
    'Stablecoin Data',
    'ステーブルコインデータ',
    '스테이블코인 데이터',
    'Dữ liệu stablecoin',
    'Данные стейблкоинов',
    'Datos de stablecoins',
    'Données sur les stablecoins',
    'Stablecoin-Daten',
    'Dados de stablecoins',
    'Stablecoin verileri',
  ],
  '数据榜': [
    '數據榜',
    'Data Rankings',
    'データランキング',
    '데이터 랭킹',
    'Xếp hạng dữ liệu',
    'Рейтинг данных',
    'Clasificación de datos',
    'Classement des données',
    'Datenrangliste',
    'Ranking de dados',
    'Veri sıralaması',
  ],
  '堆叠': [
    '堆疊',
    'Stack',
    'スタック',
    '쌓기',
    'Xếp chồng',
    'Стопка',
    'Pila',
    'Pile',
    'Stapel',
    'Pilha',
    'Yığın',
  ],
  '聚焦': [
    '聚焦',
    'Focus',
    'フォーカス',
    '집중',
    'Tập trung',
    'Фокус',
    'Enfoque',
    'Focus',
    'Fokus',
    'Foco',
    'Odak',
  ],
  '钱包': [
    '錢包',
    'Wallet',
    'ウォレット',
    '지갑',
    'Ví',
    'Кошелёк',
    'Cartera',
    'Portefeuille',
    'Wallet',
    'Carteira',
    'Cüzdan',
  ],
  '排行': [
    '排行',
    'Ranking',
    'ランキング',
    '랭킹',
    'Xếp hạng',
    'Рейтинг',
    'Ranking',
    'Classement',
    'Ranking',
    'Ranking',
    'Sıralama',
  ],
  '排行榜': [
    '排行榜',
    'Ranking',
    'ランキング',
    '랭킹',
    'Bảng xếp hạng',
    'Рейтинг',
    'Clasificación',
    'Classement',
    'Rangliste',
    'Classificação',
    'Sıralama',
  ],
  '我的': [
    '我的',
    'Profile',
    'プロフィール',
    '프로필',
    'Cá nhân',
    'Профиль',
    'Perfil',
    'Profil',
    'Profil',
    'Perfil',
    'Profil',
  ],
  '卡片等级': [
    '卡片等級',
    'Card Level',
    'カードレベル',
    '카드 등급',
    'Cấp thẻ',
    'Уровень карт',
    'Nivel de tarjeta',
    'Niveau de carte',
    'Kartenstufe',
    'Nível do cartão',
    'Kart seviyesi',
  ],
  '质量分': [
    '品質分',
    'Quality Score',
    '品質スコア',
    '품질 점수',
    'Điểm chất lượng',
    'Оценка качества',
    'Puntuación de calidad',
    'Score qualité',
    'Qualitätspunktzahl',
    'Pontuação de qualidade',
    'Kalite puanı',
  ],
  '未登录': [
    '未登入',
    'Signed out',
    '未ログイン',
    '로그아웃 상태',
    'Chưa đăng nhập',
    'Не выполнен вход',
    'Sesión cerrada',
    'Non connecté',
    'Abgemeldet',
    'Não conectado',
    'Oturum kapalı',
  ],
  '去登录': [
    '去登入',
    'Log in',
    'ログインする',
    '로그인하기',
    'Đăng nhập',
    'Войти',
    'Iniciar sesión',
    'Se connecter',
    'Anmelden',
    'Entrar',
    'Giriş yap',
  ],
  '去验证': [
    '去驗證',
    'Verify now',
    '認証する',
    '인증하기',
    'Xác minh ngay',
    'Подтвердить',
    'Verificar ahora',
    'Vérifier',
    'Jetzt bestätigen',
    'Verificar agora',
    'Doğrula',
  ],
  '显示语言': [
    '顯示語言',
    'Display Language',
    '表示言語',
    '표시 언어',
    'Ngôn ngữ hiển thị',
    'Язык интерфейса',
    'Idioma de visualización',
    'Langue d’affichage',
    'Anzeigesprache',
    'Idioma de exibição',
    'Görüntüleme dili',
  ],
  '订阅与服务': [
    '訂閱與服務',
    'Subscriptions & Services',
    'サブスクリプションとサービス',
    '구독 및 서비스',
    'Gói đăng ký & dịch vụ',
    'Подписки и сервисы',
    'Suscripciones y servicios',
    'Abonnements et services',
    'Abos & Dienste',
    'Assinaturas e serviços',
    'Abonelikler ve hizmetler',
  ],
  '版本管理': [
    '版本管理',
    'Version',
    'バージョン',
    '버전',
    'Phiên bản',
    'Версия',
    'Versión',
    'Version',
    'Version',
    'Versão',
    'Sürüm',
  ],
  '推荐卡片': [
    '推薦卡片',
    'Recommend a Card',
    'カードを推薦',
    '카드 추천',
    'Đề xuất thẻ',
    'Рекомендовать карту',
    'Recomendar tarjeta',
    'Recommander une carte',
    'Karte empfehlen',
    'Recomendar cartão',
    'Kart öner',
  ],
  '提醒配置': [
    '提醒設定',
    'Reminders',
    'リマインダー設定',
    '알림 설정',
    'Cài đặt nhắc nhở',
    'Настройки напоминаний',
    'Recordatorios',
    'Rappels',
    'Erinnerungen',
    'Lembretes',
    'Hatırlatıcılar',
  ],
  '登录后计算卡片等级': [
    '登入後計算卡片等級',
    'Log in to calculate your card level',
    'ログインしてカードレベルを計算',
    '로그인 후 카드 등급을 계산합니다',
    'Đăng nhập để tính cấp thẻ',
    'Войдите, чтобы рассчитать уровень карт',
    'Inicia sesión para calcular el nivel de tus tarjetas',
    'Connectez-vous pour calculer votre niveau de cartes',
    'Melde dich an, um deine Kartenstufe zu berechnen',
    'Entre para calcular o nível dos seus cartões',
    'Kart seviyenizi hesaplamak için giriş yapın',
  ],
  '高质量卡片组合，覆盖面和梯队都很完整': [
    '高品質卡片組合，覆蓋面和梯隊都很完整',
    'A high-quality card set with excellent coverage and depth',
    'カバー範囲と層が充実した高品質なカード構成',
    '커버리지와 구성이 탄탄한 고품질 카드 조합',
    'Bộ thẻ chất lượng cao với độ phủ và phân tầng hoàn chỉnh',
    'Качественный набор карт с отличным покрытием и глубиной',
    'Una selección de tarjetas de alta calidad, completa y equilibrada',
    'Une sélection de cartes de qualité, complète et équilibrée',
    'Ein hochwertiges Karten-Set mit starker Abdeckung und Tiefe',
    'Um conjunto de cartões de alta qualidade, completo e equilibrado',
    'Geniş kapsamlı ve dengeli yüksek kaliteli kart seti',
  ],
  '个人中心': [
    '個人中心',
    'Profile',
    'プロフィール',
    '프로필',
    'Trang cá nhân',
    'Профиль',
    'Perfil',
    'Profil',
    'Profil',
    'Perfil',
    'Profil',
  ],
  '添加卡片': [
    '新增卡片',
    'Add Card',
    'カードを追加',
    '카드 추가',
    'Thêm thẻ',
    'Добавить карту',
    'Añadir tarjeta',
    'Ajouter une carte',
    'Karte hinzufügen',
    'Adicionar cartão',
    'Kart ekle',
  ],
  '拍照识别账单': [
    '拍照識別帳單',
    'Scan Bill',
    '請求書をスキャン',
    '청구서 스캔',
    'Quét hóa đơn',
    'Сканировать счёт',
    'Escanear recibo',
    'Scanner un reçu',
    'Beleg scannen',
    'Digitalizar fatura',
    'Faturayı tara',
  ],
  '还没有卡片': [
    '還沒有卡片',
    'No cards yet',
    'カードはまだありません',
    '아직 카드가 없습니다',
    'Chưa có thẻ nào',
    'Карточек пока нет',
    'Aún no hay tarjetas',
    'Pas encore de cartes',
    'Noch keine Karten',
    'Ainda não há cartões',
    'Henüz kart yok',
  ],
  '从公开目录选择第一张卡片，数据仅保存在本机': [
    '從公開目錄選擇第一張卡片，資料僅保存在本機',
    'Choose your first card from the public catalog. Data stays on this device.',
    '公開カタログから最初のカードを選択します。データはこの端末にのみ保存されます。',
    '공개 카탈로그에서 첫 카드를 선택하세요. 데이터는 이 기기에만 저장됩니다.',
    'Chọn thẻ đầu tiên từ danh mục công khai. Dữ liệu chỉ được lưu trên thiết bị này.',
    'Выберите первую карту из общего каталога. Данные хранятся только на этом устройстве.',
    'Elige tu primera tarjeta del catálogo público. Los datos se guardan solo en este dispositivo.',
    'Choisissez votre première carte dans le catalogue public. Les données restent sur cet appareil.',
    'Wähle deine erste Karte aus dem öffentlichen Katalog. Daten bleiben nur auf diesem Gerät.',
    'Escolha seu primeiro cartão no catálogo público. Os dados ficam apenas neste dispositivo.',
    'İlk kartınızı herkese açık katalogdan seçin. Veriler yalnızca bu cihazda saklanır.',
  ],
  '暂时无法加载卡片': [
    '暫時無法載入卡片',
    'Cards could not be loaded',
    'カードを読み込めません',
    '카드를 불러올 수 없습니다',
    'Không thể tải thẻ',
    'Не удалось загрузить карты',
    'No se pudieron cargar las tarjetas',
    'Impossible de charger les cartes',
    'Karten konnten nicht geladen werden',
    'Não foi possível carregar os cartões',
    'Kartlar yüklenemedi',
  ],
  '请检查网络状态后重试。': [
    '請檢查網路狀態後重試。',
    'Check your connection and try again.',
    'ネットワーク接続を確認して、もう一度お試しください。',
    '네트워크 연결을 확인한 후 다시 시도하세요.',
    'Kiểm tra kết nối mạng rồi thử lại.',
    'Проверьте подключение к сети и повторите попытку.',
    'Comprueba tu conexión e inténtalo de nuevo.',
    'Vérifiez votre connexion et réessayez.',
    'Überprüfe deine Verbindung und versuche es erneut.',
    'Verifique sua conexão e tente novamente.',
    'Bağlantınızı kontrol edip tekrar deneyin.',
  ],
  '重新加载': [
    '重新載入',
    'Reload',
    '再読み込み',
    '다시 불러오기',
    'Tải lại',
    'Перезагрузить',
    'Recargar',
    'Recharger',
    'Neu laden',
    'Recarregar',
    'Yeniden yükle',
  ],
  '没有找到匹配卡片': [
    '沒有找到相符卡片',
    'No matching cards found',
    '一致するカードが見つかりません',
    '일치하는 카드를 찾지 못했습니다',
    'Không tìm thấy thẻ phù hợp',
    'Подходящих карт не найдено',
    'No se encontraron tarjetas coincidentes',
    'Aucune carte correspondante',
    'Keine passenden Karten gefunden',
    'Nenhum cartão correspondente encontrado',
    'Eşleşen kart bulunamadı',
  ],
  '换个关键词或分类试试': [
    '換個關鍵字或分類試試',
    'Try another keyword or category',
    '別のキーワードやカテゴリーをお試しください',
    '다른 검색어나 카테고리를 시도해 보세요',
    'Thử từ khóa hoặc danh mục khác',
    'Попробуйте другое ключевое слово или категорию',
    'Prueba con otra palabra clave o categoría',
    'Essayez un autre mot-clé ou une autre catégorie',
    'Versuche ein anderes Stichwort oder eine andere Kategorie',
    'Tente outra palavra-chave ou categoria',
    'Başka bir anahtar kelime veya kategori deneyin',
  ],
  '返回': [
    '返回',
    'Back',
    '戻る',
    '뒤로',
    'Quay lại',
    'Назад',
    'Atrás',
    'Retour',
    'Zurück',
    'Voltar',
    'Geri',
  ],
  '关闭': [
    '關閉',
    'Close',
    '閉じる',
    '닫기',
    'Đóng',
    'Закрыть',
    'Cerrar',
    'Fermer',
    'Schließen',
    'Fechar',
    'Kapat',
  ],
  '完成': [
    '完成',
    'Done',
    '完了',
    '완료',
    'Xong',
    'Готово',
    'Listo',
    'Terminé',
    'Fertig',
    'Concluído',
    'Bitti',
  ],
  '取消': [
    '取消',
    'Cancel',
    'キャンセル',
    '취소',
    'Hủy',
    'Отмена',
    'Cancelar',
    'Annuler',
    'Abbrechen',
    'Cancelar',
    'İptal',
  ],
  '确认': [
    '確認',
    'Confirm',
    '確認',
    '확인',
    'Xác nhận',
    'Подтвердить',
    'Confirmar',
    'Confirmer',
    'Bestätigen',
    'Confirmar',
    'Onayla',
  ],
  '保存': [
    '儲存',
    'Save',
    '保存',
    '저장',
    'Lưu',
    'Сохранить',
    'Guardar',
    'Enregistrer',
    'Speichern',
    'Salvar',
    'Kaydet',
  ],
  '删除': [
    '刪除',
    'Delete',
    '削除',
    '삭제',
    'Xóa',
    'Удалить',
    'Eliminar',
    'Supprimer',
    'Löschen',
    'Excluir',
    'Sil',
  ],
  '搜索': [
    '搜尋',
    'Search',
    '検索',
    '검색',
    'Tìm kiếm',
    'Поиск',
    'Buscar',
    'Rechercher',
    'Suchen',
    'Pesquisar',
    'Ara',
  ],
  '全部': [
    '全部',
    'All',
    'すべて',
    '전체',
    'Tất cả',
    'Все',
    'Todo',
    'Tout',
    'Alle',
    'Todos',
    'Tümü',
  ],
  '热门': [
    '熱門',
    'Hot',
    '人気',
    '인기',
    'Phổ biến',
    'Популярное',
    'Popular',
    'Populaire',
    'Beliebt',
    'Em alta',
    'Popüler',
  ],
  '上新': [
    '上新',
    'New',
    '新着',
    '신규',
    'Mới',
    'Новинки',
    'Nuevo',
    'Nouveau',
    'Neu',
    'Novos',
    'Yeni',
  ],
  '其他': [
    '其他',
    'Other',
    'その他',
    '기타',
    'Khác',
    'Другое',
    'Otros',
    'Autres',
    'Andere',
    'Outros',
    'Diğer',
  ],
  '卡片': [
    '卡片',
    'Cards',
    'カード',
    '카드',
    'Thẻ',
    'Карты',
    'Tarjetas',
    'Cartes',
    'Karten',
    'Cartões',
    'Kartlar',
  ],
  '文章': [
    '文章',
    'Articles',
    '記事',
    '게시물',
    'Bài viết',
    'Статьи',
    'Artículos',
    'Articles',
    'Artikel',
    'Artigos',
    'Makaleler',
  ],
  '资讯': [
    '資訊',
    'News',
    'ニュース',
    '뉴스',
    'Tin tức',
    'Новости',
    'Noticias',
    'Actualités',
    'News',
    'Notícias',
    'Haberler',
  ],
  '福利': [
    '福利',
    'Benefits',
    '特典',
    '혜택',
    'Ưu đãi',
    'Преимущества',
    'Beneficios',
    'Avantages',
    'Vorteile',
    'Benefícios',
    'Avantajlar',
  ],
  '开卡': [
    '開卡',
    'Get a Card',
    'カード申請',
    '카드 발급',
    'Mở thẻ',
    'Оформление карты',
    'Solicitar tarjeta',
    'Obtenir une carte',
    'Karte beantragen',
    'Solicitar cartão',
    'Kart başvurusu',
  ],
  '稳定币总市值': [
    '穩定幣總市值',
    'Total Stablecoin Market Cap',
    'ステーブルコイン時価総額',
    '스테이블코인 총 시가총액',
    'Tổng vốn hóa stablecoin',
    'Общая капитализация стейблкоинов',
    'Capitalización total de stablecoins',
    'Capitalisation totale des stablecoins',
    'Gesamte Stablecoin-Marktkapitalisierung',
    'Capitalização total de stablecoins',
    'Toplam stablecoin piyasa değeri',
  ],
  '当前区间趋势': [
    '目前區間趨勢',
    'Current Period Trend',
    '現在の期間トレンド',
    '현재 구간 추세',
    'Xu hướng kỳ hiện tại',
    'Тренд за период',
    'Tendencia del periodo actual',
    'Tendance de la période',
    'Aktueller Zeitraumtrend',
    'Tendência do período atual',
    'Mevcut dönem eğilimi',
  ],
  '区间增长': [
    '區間增長',
    'Period Change',
    '期間増加率',
    '기간 변동',
    'Thay đổi kỳ',
    'Изменение за период',
    'Cambio del periodo',
    'Variation de période',
    'Zeitraumänderung',
    'Variação do período',
    'Dönem değişimi',
  ],
  '24h 交易量': [
    '24h 交易量',
    '24h Volume',
    '24時間取引量',
    '24시간 거래량',
    'Khối lượng 24h',
    'Объём за 24 ч',
    'Volumen 24 h',
    'Volume 24 h',
    '24h-Volumen',
    'Volume em 24h',
    '24sa hacim',
  ],
  '收录资产': [
    '收錄資產',
    'Tracked Assets',
    '収録資産',
    '추적 자산',
    'Tài sản theo dõi',
    'Отслеживаемые активы',
    'Activos seguidos',
    'Actifs suivis',
    'Erfasste Assets',
    'Ativos monitorados',
    'İzlenen varlıklar',
  ],
  '数据来源：': [
    '數據來源：',
    'Source: ',
    'データソース：',
    '데이터 출처: ',
    'Nguồn: ',
    'Источник: ',
    'Fuente: ',
    'Source : ',
    'Quelle: ',
    'Fonte: ',
    'Kaynak: ',
  ],
  '更新时间：': [
    '更新時間：',
    'Updated: ',
    '更新時刻：',
    '업데이트: ',
    'Cập nhật: ',
    'Обновлено: ',
    'Actualizado: ',
    'Mis à jour : ',
    'Aktualisiert: ',
    'Atualizado: ',
    'Güncelleme: ',
  ],
  '设置': [
    '設定',
    'Settings',
    '設定',
    '설정',
    'Cài đặt',
    'Настройки',
    'Ajustes',
    'Réglages',
    'Einstellungen',
    'Configurações',
    'Ayarlar',
  ],
  '语言': [
    '語言',
    'Language',
    '言語',
    '언어',
    'Ngôn ngữ',
    'Язык',
    'Idioma',
    'Langue',
    'Sprache',
    'Idioma',
    'Dil',
  ],
  '语言设置': [
    '語言設定',
    'Language',
    '言語設定',
    '언어 설정',
    'Ngôn ngữ',
    'Язык',
    'Idioma',
    'Langue',
    'Sprache',
    'Idioma',
    'Dil',
  ],
  '跟随系统': [
    '跟隨系統',
    'System default',
    'システム設定',
    '시스템 설정',
    'Theo hệ thống',
    'Как в системе',
    'Sistema',
    'Système',
    'System',
    'Sistema',
    'Sistem',
  ],
  '系统': [
    '系統',
    'System',
    'システム',
    '시스템',
    'Hệ thống',
    'Система',
    'Sistema',
    'Système',
    'System',
    'Sistema',
    'Sistem',
  ],
  '简体中文': [
    '簡體中文',
    'Simplified Chinese',
    '簡体字中国語',
    '중국어 간체',
    'Tiếng Trung giản thể',
    'Китайский (упр.)',
    'Chino simplificado',
    'Chinois simplifié',
    'Chinesisch (vereinfacht)',
    'Chinês simplificado',
    'Basitleştirilmiş Çince',
  ],
  '繁體中文': [
    '繁體中文',
    'Traditional Chinese',
    '繁体字中国語',
    '중국어 번체',
    'Tiếng Trung phồn thể',
    'Китайский (трад.)',
    'Chino tradicional',
    'Chinois traditionnel',
    'Chinesisch (traditionell)',
    'Chinês tradicional',
    'Geleneksel Çince',
  ],
  '当前语言': [
    '目前語言',
    'Current language',
    '現在の言語',
    '현재 언어',
    'Ngôn ngữ hiện tại',
    'Текущий язык',
    'Idioma actual',
    'Langue actuelle',
    'Aktuelle Sprache',
    'Idioma atual',
    'Geçerli dil',
  ],
  '用户名': [
    '使用者名稱',
    'Username',
    'ユーザー名',
    '사용자 이름',
    'Tên người dùng',
    'Имя пользователя',
    'Nombre de usuario',
    'Nom d’utilisateur',
    'Benutzername',
    'Nome de usuário',
    'Kullanıcı adı',
  ],
  '修改用户名': [
    '修改使用者名稱',
    'Edit Username',
    'ユーザー名を変更',
    '사용자 이름 변경',
    'Đổi tên người dùng',
    'Изменить имя пользователя',
    'Editar nombre de usuario',
    'Modifier le nom d’utilisateur',
    'Benutzernamen ändern',
    'Editar nome de usuário',
    'Kullanıcı adını değiştir',
  ],
  '输入新的用户名': [
    '輸入新的使用者名稱',
    'Enter a new username',
    '新しいユーザー名を入力',
    '새 사용자 이름 입력',
    'Nhập tên người dùng mới',
    'Введите новое имя пользователя',
    'Introduce un nombre de usuario nuevo',
    'Saisissez un nouveau nom d’utilisateur',
    'Neuen Benutzernamen eingeben',
    'Digite um novo nome de usuário',
    'Yeni kullanıcı adı girin',
  ],
  '用户名已更新。': [
    '使用者名稱已更新。',
    'Username updated.',
    'ユーザー名を更新しました。',
    '사용자 이름이 업데이트되었습니다.',
    'Đã cập nhật tên người dùng.',
    'Имя пользователя обновлено.',
    'Nombre de usuario actualizado.',
    'Nom d’utilisateur mis à jour.',
    'Benutzername aktualisiert.',
    'Nome de usuário atualizado.',
    'Kullanıcı adı güncellendi.',
  ],
  '语言偏好已保存': [
    '語言偏好已儲存',
    'Language saved',
    '言語を保存しました',
    '언어가 저장되었습니다',
    'Đã lưu ngôn ngữ',
    'Язык сохранён',
    'Idioma guardado',
    'Langue enregistrée',
    'Sprache gespeichert',
    'Idioma salvo',
    'Dil kaydedildi',
  ],
  '系统会记住你的语言选择，并应用到整个 App。': [
    '系統會記住你的語言選擇，並套用至整個 App。',
    'Your language choice is saved and applied throughout the app.',
    '言語設定は保存され、アプリ全体に適用されます。',
    '선택한 언어는 저장되어 앱 전체에 적용됩니다.',
    'Lựa chọn ngôn ngữ được lưu và áp dụng cho toàn bộ ứng dụng.',
    'Выбранный язык сохранится и будет применён во всём приложении.',
    'Tu idioma se guarda y se aplica en toda la aplicación.',
    'Votre choix de langue est enregistré et appliqué dans toute l’application.',
    'Deine Sprachwahl wird gespeichert und in der gesamten App angewendet.',
    'Sua escolha de idioma é salva e aplicada em todo o app.',
    'Dil seçiminiz kaydedilir ve uygulamanın tamamına uygulanır.',
  ],
  '深色模式': [
    '深色模式',
    'Dark mode',
    'ダークモード',
    '다크 모드',
    'Chế độ tối',
    'Тёмная тема',
    'Modo oscuro',
    'Mode sombre',
    'Dunkelmodus',
    'Modo escuro',
    'Koyu mod',
  ],
  '浅色模式': [
    '淺色模式',
    'Light mode',
    'ライトモード',
    '라이트 모드',
    'Chế độ sáng',
    'Светлая тема',
    'Modo claro',
    'Mode clair',
    'Hellmodus',
    'Modo claro',
    'Açık mod',
  ],
  '登录': [
    '登入',
    'Log in',
    'ログイン',
    '로그인',
    'Đăng nhập',
    'Войти',
    'Iniciar sesión',
    'Connexion',
    'Anmelden',
    'Entrar',
    'Giriş yap',
  ],
  '退出登录': [
    '登出',
    'Log out',
    'ログアウト',
    '로그아웃',
    'Đăng xuất',
    'Выйти',
    'Cerrar sesión',
    'Déconnexion',
    'Abmelden',
    'Sair',
    'Çıkış yap',
  ],
  '创建账号': [
    '建立帳號',
    'Create account',
    'アカウント作成',
    '계정 만들기',
    'Tạo tài khoản',
    'Создать аккаунт',
    'Crear cuenta',
    'Créer un compte',
    'Konto erstellen',
    'Criar conta',
    'Hesap oluştur',
  ],
  '密码': [
    '密碼',
    'Password',
    'パスワード',
    '비밀번호',
    'Mật khẩu',
    'Пароль',
    'Contraseña',
    'Mot de passe',
    'Passwort',
    'Senha',
    'Şifre',
  ],
  '忘记密码': [
    '忘記密碼',
    'Forgot password',
    'パスワードを忘れた',
    '비밀번호 찾기',
    'Quên mật khẩu',
    'Забыли пароль',
    'Olvidé mi contraseña',
    'Mot de passe oublié',
    'Passwort vergessen',
    'Esqueci a senha',
    'Şifremi unuttum',
  ],
  '显示密码': [
    '顯示密碼',
    'Show password',
    'パスワードを表示',
    '비밀번호 표시',
    'Hiện mật khẩu',
    'Показать пароль',
    'Mostrar contraseña',
    'Afficher le mot de passe',
    'Passwort anzeigen',
    'Mostrar senha',
    'Şifreyi göster',
  ],
  '隐藏密码': [
    '隱藏密碼',
    'Hide password',
    'パスワードを非表示',
    '비밀번호 숨기기',
    'Ẩn mật khẩu',
    'Скрыть пароль',
    'Ocultar contraseña',
    'Masquer le mot de passe',
    'Passwort ausblenden',
    'Ocultar senha',
    'Şifreyi gizle',
  ],
  '未登录用户': [
    '未登入使用者',
    'Guest',
    'ゲスト',
    '게스트',
    'Khách',
    'Гость',
    'Invitado',
    'Invité',
    'Gast',
    'Visitante',
    'Misafir',
  ],
  '当前未登录': [
    '目前未登入',
    'Signed out',
    'ログアウト中',
    '로그아웃 상태',
    'Chưa đăng nhập',
    'Вы не вошли',
    'Sesión cerrada',
    'Non connecté',
    'Abgemeldet',
    'Não conectado',
    'Oturum kapalı',
  ],
  '当前未登录 · 登录后同步卡片与收藏': [
    '目前未登入 · 登入後同步卡片與收藏',
    'Signed out · Log in to sync cards and favorites',
    '未ログイン · ログインしてカードとお気に入りを同期',
    '로그아웃 상태 · 로그인 후 카드와 즐겨찾기를 동기화',
    'Chưa đăng nhập · Đăng nhập để đồng bộ thẻ và yêu thích',
    'Вы не вошли · Войдите для синхронизации карт и избранного',
    'Sesión cerrada · Inicia sesión para sincronizar tarjetas y favoritos',
    'Non connecté · Connectez-vous pour synchroniser vos cartes et favoris',
    'Abgemeldet · Melde dich an, um Karten und Favoriten zu synchronisieren',
    'Não conectado · Entre para sincronizar cartões e favoritos',
    'Oturum kapalı · Kartları ve favorileri eşitlemek için giriş yapın',
  ],
  '可管理卡片与收藏': [
    '可管理卡片與收藏',
    'Manage cards and favorites',
    'カードとお気に入りを管理',
    '카드와 즐겨찾기 관리',
    'Quản lý thẻ và yêu thích',
    'Управление картами и избранным',
    'Gestiona tarjetas y favoritos',
    'Gérez vos cartes et favoris',
    'Karten und Favoriten verwalten',
    'Gerencie cartões e favoritos',
    'Kartları ve favorileri yönetin',
  ],
  '邮箱待验证': [
    '信箱待驗證',
    'Email verification pending',
    'メール認証待ち',
    '이메일 인증 대기 중',
    'Chờ xác minh email',
    'Ожидается подтверждение email',
    'Verificación de correo pendiente',
    'Vérification de l’e-mail en attente',
    'E-Mail-Bestätigung ausstehend',
    'Verificação de e-mail pendente',
    'E-posta doğrulaması bekliyor',
  ],
  '我的收藏': [
    '我的收藏',
    'Favorites',
    'お気に入り',
    '즐겨찾기',
    'Yêu thích',
    'Избранное',
    'Favoritos',
    'Favoris',
    'Favoriten',
    'Favoritos',
    'Favoriler',
  ],
  '收藏': [
    '收藏',
    'Favorite',
    'お気に入り',
    '즐겨찾기',
    'Yêu thích',
    'Избранное',
    'Favorito',
    'Favori',
    'Favorit',
    'Favorito',
    'Favori',
  ],
  '浏览记录': [
    '瀏覽記錄',
    'History',
    '閲覧履歴',
    '기록',
    'Lịch sử',
    'История',
    'Historial',
    'Historique',
    'Verlauf',
    'Histórico',
    'Geçmiş',
  ],
  '消息与反馈': [
    '訊息與回饋',
    'Messages & Feedback',
    'メッセージとフィードバック',
    '메시지 및 피드백',
    'Tin nhắn & phản hồi',
    'Сообщения и отзывы',
    'Mensajes y comentarios',
    'Messages et avis',
    'Nachrichten & Feedback',
    'Mensagens e feedback',
    'Mesajlar ve geri bildirim',
  ],
  '帮助中心': [
    '說明中心',
    'Help',
    'ヘルプ',
    '도움말',
    'Trợ giúp',
    'Помощь',
    'Ayuda',
    'Aide',
    'Hilfe',
    'Ajuda',
    'Yardım',
  ],
  '关于我们': [
    '關於我們',
    'About',
    'このアプリについて',
    '정보',
    'Giới thiệu',
    'О приложении',
    'Acerca de',
    'À propos',
    'Über uns',
    'Sobre',
    'Hakkında',
  ],
  '通知': [
    '通知',
    'Notifications',
    '通知',
    '알림',
    'Thông báo',
    'Уведомления',
    'Notificaciones',
    'Notifications',
    'Benachrichtigungen',
    'Notificações',
    'Bildirimler',
  ],
  '已开启': [
    '已開啟',
    'On',
    'オン',
    '켜짐',
    'Bật',
    'Вкл.',
    'Activado',
    'Activé',
    'Ein',
    'Ativado',
    'Açık',
  ],
  '未设置': [
    '未設定',
    'Not set',
    '未設定',
    '설정 안 됨',
    'Chưa đặt',
    'Не задано',
    'Sin configurar',
    'Non défini',
    'Nicht festgelegt',
    'Não definido',
    'Ayarlanmadı',
  ],
  '加载中': [
    '載入中',
    'Loading',
    '読み込み中',
    '로딩 중',
    'Đang tải',
    'Загрузка',
    'Cargando',
    'Chargement',
    'Wird geladen',
    'Carregando',
    'Yükleniyor',
  ],
  '请稍候…': [
    '請稍候…',
    'Please wait…',
    'お待ちください…',
    '잠시만 기다려 주세요…',
    'Vui lòng đợi…',
    'Подождите…',
    'Espera…',
    'Veuillez patienter…',
    'Bitte warten…',
    'Aguarde…',
    'Lütfen bekleyin…',
  ],
  '卡片详情': [
    '卡片詳情',
    'Card Details',
    'カード詳細',
    '카드 상세',
    'Chi tiết thẻ',
    'О карте',
    'Detalles de la tarjeta',
    'Détails de la carte',
    'Kartendetails',
    'Detalhes do cartão',
    'Kart ayrıntıları',
  ],
  '更多操作': [
    '更多操作',
    'More actions',
    'その他の操作',
    '추가 작업',
    'Thao tác khác',
    'Другие действия',
    'Más acciones',
    'Plus d’actions',
    'Weitere Aktionen',
    'Mais ações',
    'Diğer işlemler',
  ],
  '基本信息': [
    '基本資訊',
    'Basic information',
    '基本情報',
    '기본 정보',
    'Thông tin cơ bản',
    'Основная информация',
    'Información básica',
    'Informations de base',
    'Grundinformationen',
    'Informações básicas',
    'Temel bilgiler',
  ],
  '费用': [
    '費用',
    'Fees',
    '手数料',
    '수수료',
    'Phí',
    'Комиссии',
    'Comisiones',
    'Frais',
    'Gebühren',
    'Taxas',
    'Ücretler',
  ],
  '核心权益': [
    '核心權益',
    'Key benefits',
    '主な特典',
    '주요 혜택',
    'Quyền lợi chính',
    'Главные преимущества',
    'Beneficios clave',
    'Avantages clés',
    'Wichtigste Vorteile',
    'Principais benefícios',
    'Temel avantajlar',
  ],
  '适用地区': [
    '適用地區',
    'Region',
    '対象地域',
    '지원 지역',
    'Khu vực',
    'Регион',
    'Región',
    'Région',
    'Region',
    'Região',
    'Bölge',
  ],
  '卡片类型': [
    '卡片類型',
    'Card type',
    'カード種類',
    '카드 유형',
    'Loại thẻ',
    'Тип карты',
    'Tipo de tarjeta',
    'Type de carte',
    'Kartentyp',
    'Tipo de cartão',
    'Kart türü',
  ],
  '支付渠道': [
    '支付管道',
    'Payment support',
    '決済対応',
    '결제 지원',
    'Hỗ trợ thanh toán',
    'Поддержка оплаты',
    'Métodos de pago',
    'Moyens de paiement',
    'Zahlungsunterstützung',
    'Meios de pagamento',
    'Ödeme desteği',
  ],
  '来源': [
    '來源',
    'Source',
    '出典',
    '출처',
    'Nguồn',
    'Источник',
    'Fuente',
    'Source',
    'Quelle',
    'Fonte',
    'Kaynak',
  ],
  '以官网为准': [
    '以官網為準',
    'See official site',
    '公式サイトをご確認ください',
    '공식 사이트를 확인하세요',
    'Theo trang chính thức',
    'См. официальный сайт',
    'Consulta el sitio oficial',
    'Voir le site officiel',
    'Siehe offizielle Website',
    'Consulte o site oficial',
    'Resmî siteye bakın',
  ],
  'Pro 会员': [
    'Pro 會員',
    'Pro Membership',
    'Proメンバーシップ',
    'Pro 멤버십',
    'Gói Pro',
    'Подписка Pro',
    'Membresía Pro',
    'Abonnement Pro',
    'Pro-Mitgliedschaft',
    'Assinatura Pro',
    'Pro Üyelik',
  ],
  '恢复购买': [
    '恢復購買',
    'Restore purchases',
    '購入を復元',
    '구매 복원',
    'Khôi phục giao dịch',
    'Восстановить покупки',
    'Restaurar compras',
    'Restaurer les achats',
    'Käufe wiederherstellen',
    'Restaurar compras',
    'Satın alımları geri yükle',
  ],
  '管理订阅': [
    '管理訂閱',
    'Manage subscription',
    'サブスクリプション管理',
    '구독 관리',
    'Quản lý đăng ký',
    'Управление подпиской',
    'Gestionar suscripción',
    'Gérer l’abonnement',
    'Abo verwalten',
    'Gerenciar assinatura',
    'Aboneliği yönet',
  ],
};

String _translatePattern(String source, Locale locale) {
  if (locale.languageCode == 'zh') return _toTraditional(source);

  final index = _languageIndex(locale);
  const cardModePrefixes = [
    '切換卡片模式，目前',
    'Switch card mode, current: ',
    'カード表示を切替：',
    '카드 보기 전환, 현재: ',
    'Chuyển chế độ thẻ, hiện tại: ',
    'Сменить режим карт, текущий: ',
    'Cambiar modo de tarjetas, actual: ',
    'Changer le mode des cartes, actuel : ',
    'Kartenmodus wechseln, aktuell: ',
    'Alternar modo dos cartões, atual: ',
    'Kart modunu değiştir, mevcut: ',
  ];
  if (source.startsWith('切换卡片模式，当前')) {
    return '${cardModePrefixes[index]}${textForLocale(source.substring('切换卡片模式，当前'.length), locale)}';
  }
  final ownedCards = RegExp(r'^已持有 (\\d+) 张卡片$').firstMatch(source);
  if (ownedCards != null) {
    final count = ownedCards.group(1)!;
    final labels = [
      '已持有 $count 張卡片',
      '$count cards owned',
      '$count 枚のカードを所有',
      '보유 카드 $count장',
      'Đã có $count thẻ',
      'Карт в наличии: $count',
      '$count tarjetas',
      '$count cartes',
      '$count Karten',
      '$count cartões',
      '$count kart',
    ];
    return labels[index];
  }
  final favoriteCards = RegExp(r'^收藏 (\\d+) 张$').firstMatch(source);
  if (favoriteCards != null) {
    final count = favoriteCards.group(1)!;
    final labels = [
      '收藏 $count 張',
      '$count favorites',
      'お気に入り $count 枚',
      '즐겨찾기 $count장',
      '$count yêu thích',
      'В избранном: $count',
      '$count favoritos',
      '$count favoris',
      '$count Favoriten',
      '$count favoritos',
      '$count favori',
    ];
    return labels[index];
  }
  const displayLanguagePrefixes = [
    '顯示語言已設為 ',
    'Display language set to ',
    '表示言語を設定しました：',
    '표시 언어: ',
    'Đã đặt ngôn ngữ: ',
    'Язык интерфейса: ',
    'Idioma configurado: ',
    'Langue définie : ',
    'Anzeigesprache: ',
    'Idioma definido: ',
    'Görüntüleme dili: ',
  ];
  if (source.startsWith('显示语言已设为 ')) {
    return '${displayLanguagePrefixes[index]}${source.substring('显示语言已设为 '.length)}';
  }
  const systemLanguagePrefixes = [
    '已跟隨系統語言：',
    'Following system language: ',
    'システム言語：',
    '시스템 언어: ',
    'Theo ngôn ngữ hệ thống: ',
    'Язык системы: ',
    'Idioma del sistema: ',
    'Langue du système : ',
    'Systemsprache: ',
    'Idioma do sistema: ',
    'Sistem dili: ',
  ];
  if (source.startsWith('已跟随系统语言：')) {
    return '${systemLanguagePrefixes[index]}${source.substring('已跟随系统语言：'.length)}';
  }
  var value = source;
  if (locale.languageCode == 'en') {
    final fallbacks = _englishFallbackPhrases.entries.toList(growable: false)
      ..sort((a, b) => b.key.length.compareTo(a.key.length));
    for (final entry in fallbacks) {
      value = value.replaceAll(entry.key, entry.value);
    }
  }
  final entries = _catalog.entries.toList(growable: false)
    ..sort((a, b) => b.key.length.compareTo(a.key.length));
  for (final entry in entries) {
    if (value.contains(entry.key)) {
      value = value.replaceAll(entry.key, entry.value[index]);
    }
  }
  return value;
}

/// Safety net for product copy that is composed dynamically or has not yet
/// been promoted to a full multi-locale catalog entry. Keep this English-only:
/// other locales must continue using their reviewed catalog translations.
const _englishFallbackPhrases = <String, String>{
  'AI 选卡': 'AI Card Match',
  '告诉我你的条件': 'Tell us your needs',
  'AI 会从集卡已收录的公开资料里筛选适合进一步了解的卡片，并列出需要到官方页面确认的限制。':
      'AI matches cards from Card Hub’s published information and highlights limits to confirm on official pages.',
  '所在地': 'Location',
  '中国大陆': 'Mainland China',
  '港澳台': 'Hong Kong, Macao & Taiwan',
  '海外': 'Overseas',
  '可使用证件': 'Available document',
  '护照': 'Passport',
  '身份证': 'National ID',
  '暂不确定': 'Not sure yet',
  '主要用途': 'Primary use',
  '日常消费': 'Daily spending',
  '线上订阅': 'Online subscriptions',
  '旅行消费': 'Travel spending',
  '收付款': 'Receiving & paying',
  'KYC 偏好': 'KYC preference',
  '可接受 KYC': 'KYC is acceptable',
  '希望流程简单': 'Prefer a simple process',
  '补充条件（可选）': 'Additional details (optional)',
  '例如：希望优先了解线上消费、地区限制或费率说明。请不要填写证件号、卡号、密码等敏感信息。':
      'For example: online spending, region limits, or fees. Do not enter ID numbers, card numbers, passwords, or other sensitive details.',
  '正在匹配公开资料…': 'Matching published information…',
  '生成 AI 选卡建议': 'Get AI card matches',
  '不会上传证件、卡号或密码。建议仅按你填写的条件与收录资料生成。':
      'Do not enter documents, card numbers, or passwords. Advice uses only your selections and published card information.',
  '匹配结果': 'Matches',
  '当前公开资料不足以匹配具体卡片。建议补充用途后重试，并直接查看卡片目录。':
      'Published information is not enough to match a specific card. Add more detail or browse the card catalog directly.',
  '下一步确认': 'Confirm next',
  '需确认：': 'Confirm: ',
  '请先登录并完成邮箱验证后使用 AI 选卡':
      'Sign in and verify your email before using AI Card Match.',
  '去登录': 'Sign in',
  '资料来源：': 'Sources: ',
  '浏览 ': 'Views ',
  '点赞 ': 'Likes ',
  '（前 ': ' (Top ',
  '）': ')',
  'U 卡': 'U Card',
  '已选 ': 'Selected ',
  '版本 ': 'Version ',
  '构建 ': 'Build ',
  '已提交': 'Submitted',
  ' 张': ' cards',
  '月': '/',
  '日 ': ' ',
  '网络详情暂不可用，当前显示随包资料。':
      'Online details are temporarily unavailable. Showing bundled information.',
  '公开资料整理，具体信息以发卡方为准。':
      'Compiled from public information. Refer to the issuer for final details.',
  '公开卡片资料、来源、风险提示和基础浏览不会设置付费墙。价格以 App Store 或 Google Play 显示为准。':
      'Public card information, sources, risk notices and basic browsing remain free. Prices are shown by the App Store or Google Play.',
  '订阅会按所选周期自动续费；可随时前往系统订阅管理页取消。实际价格、扣款时间与续费规则以商店确认页为准。':
      'Subscriptions renew automatically for the selected period. Cancel anytime in system subscription settings. Store confirmation controls pricing and renewal.',
  '集中管理高级对比、变更关注、离线资料和云备份。这里的评分只衡量卡包结构与资料完整度，不代表收益或申请成功率。':
      'Manage advanced comparisons, change tracking, offline information and cloud backup. Scores only measure wallet structure and data completeness.',
  'AI 只提取截图中明确显示的金额、币种、费率和手续费；损耗由固定公式计算，不让模型猜测。':
      'AI extracts only amounts, currencies, rates and fees clearly shown in the screenshot. Costs use fixed formulas, not model guesses.',
  '截图会发送到服务端和第三方 AI 进行一次性识别；App 不会把原图保存到账单记录。':
      'The screenshot is sent to the server and a third-party AI for one-time recognition. The original image is not saved to bill history.',
  '我已确认截图不包含完整卡号、姓名、订单号或其他不必要的敏感信息':
      'I confirm the screenshot does not contain a full card number, name, order number or other unnecessary sensitive information',
  '可同时选择 2–4 张卡片，差异项会被轻量标记。申请前仍请以官方最新规则为准。':
      'Select 2–4 cards. Differences are highlighted lightly. Check the latest official terms before applying.',
  '仅计算资料中能够明确识别的数字费用；币种沿用原始资料，不参与汇率换算。':
      'Only clearly identified numeric fees are calculated. Original currencies are preserved without FX conversion.',
  '请说明需要更新的字段，并尽量附上官方公开来源。内容会先保存到本机。':
      'Describe the field that needs updating and include an official public source when possible. It will be saved on this device first.',
  '当前不会上传；可在“消息与反馈”中查看或删除。':
      'Not uploaded yet. View or delete it under Messages & Feedback.',
  '当前不会上传；保存后可在“消息与反馈”中管理。':
      'Not uploaded yet. Manage it under Messages & Feedback after saving.',
  '这些记录仅保存在本机，当前不会上传。':
      'These records stay on this device and are not uploaded.',
  '退出后仍可使用本机卡包；重新登录即可恢复账号功能。':
      'Your local card wallet remains available after signing out. Sign in again to restore account features.',
  '这会永久删除账号及已同步的卡包、收藏、历史、反馈和 Pro 工作区数据，无法恢复。已有应用商店订阅不会自动取消。':
      'This permanently deletes the account and synced wallet, favorites, history, feedback and Pro workspace data. Store subscriptions are not cancelled automatically.',
  '公开发布后，新版本将通过 App Store 或 Google Play 安装。App 不会绕过应用商店静默更新。':
      'After public release, updates are installed through the App Store or Google Play. The app does not silently bypass the stores.',
  '文章里提到的卡片可以直接点进去查看详情。':
      'Open cards mentioned in the article to view their details.',
  '本文仅整理公开信息，不构成金融建议。':
      'This article compiles public information and is not financial advice.',
  '尝试更换名称、发行方或卡片类型。': 'Try another name, issuer or card type.',
  '拖动滑杆调整卡片密度，画布会保持居中。':
      'Drag the slider to adjust card density while keeping the canvas centered.',
  '已按系统“减少动态效果”设置停用自动播放':
      'Autoplay is disabled by the system Reduce Motion setting',
  '让画布更像铺开的实体卡片': 'Make the canvas feel like physical cards spread out',
  '从卡片目录添加到你的收藏': 'Add cards from the catalog to your collection',
  '暂时无法读取版本信息': 'Version information is temporarily unavailable',
  '永久删除账号？': 'Permanently delete account?',
  '正在删除账号…': 'Deleting account…',
  '永久删除': 'Delete permanently',
  '确认删除': 'Confirm deletion',
  '正在退出…': 'Signing out…',
  '重新读取': 'Reload',
  '复制版本信息': 'Copy version information',
  '提交反馈': 'Submit feedback',
  '写留言': 'Write a message',
  '通知与反馈': 'Notifications & Feedback',
  '更新方式': 'Update method',
  '当前系统：': 'Current system: ',
  '卡片滑动强度': 'Card swipe intensity',
  '卡片对比': 'Card Comparison',
  '交换前两张': 'Swap first two',
  '点击更换': 'Tap to replace',
  '保存方案': 'Save preset',
  '导出 CSV': 'Export CSV',
  '费用场景测算': 'Fee scenario estimate',
  '有差异': 'Different',
  '选择对比卡片': 'Select cards to compare',
  '没有匹配的卡片': 'No matching cards',
  '没有找到相关卡片': 'No related cards found',
  '暂时无法加载卡片': 'Unable to load cards right now',
  '请检查网络状态后重试。': 'Check your connection and try again.',
  '换个关键词或分类试试': 'Try another keyword or category',
  '已在本机卡包 · 管理': 'In your card wallet · Manage',
  '卡面效果': 'Card appearance',
  '身份验证（KYC）': 'Identity Verification (KYC)',
  '查看来源': 'View source',
  '资料来源 · ': 'Sources · ',
  '官网': 'Official site',
  '重试': 'Retry',
  '消费账单分析': 'Spending Bill Analysis',
  '识别真实消费成本': 'Identify the real cost of spending',
  '选择消费截图': 'Choose spending screenshot',
  '正在识别…': 'Recognizing…',
  '正在加载': 'Loading',
  '正在整理卡片数据': 'Preparing card data',
  'Pro 权益': 'Pro Benefits',
  '订阅服务': 'Subscription',
  '购买由系统应用商店安全处理': 'Purchase securely handled by the system app store',
  '集卡 Pro': 'Card Hub Pro',
  '接入状态': 'Connection status',
  '会员服务条款': 'Membership Terms',
  '隐私政策': 'Privacy Policy',
  'Pro 工作区': 'Pro Workspace',
  '开始对比': 'Start comparing',
  '管理规则变更关注': 'Manage change tracking',
  '管理': 'Manage',
  '纠正信息': 'Correction information',
  '提交纠错': 'Submit correction',
  '关联卡片': 'Related cards',
  '复制': 'Copy',
  '上传背景图': 'Upload background image',
  '暂无可展示的卡片': 'No cards to display',
  '轻微旋转与错位': 'Subtle rotation and offset',
  '旋转角度': 'Rotation angle',
  '自定义颜色': 'Custom color',
  '停止播放': 'Stop playback',
  '自动': 'Auto',
  '使用': 'Use',
  '暂无公开排行': 'No public ranking yet',
  '当前区间趋势': 'Current range trend',
  '数据来源：': 'Data source: ',
  '更新时间：': 'Updated: ',
  '资产筛选': 'Asset filters',
  '稳定币列表': 'Stablecoin list',
  '没有匹配的稳定币': 'No matching stablecoins',
  '历史供应趋势': 'Historical supply trend',
  '趋势数据加载失败': 'Failed to load trend data',
  '市场趋势': 'Market trend',
  '按 30 天充值量排序 · 来源 ': 'Ranked by 30-day deposit volume · Source ',
  '数据榜': 'Data Rankings',
  '资讯': 'News',
  '我': 'Me',
  '返回首页': 'Back to Home',
  '账户': 'Account',
};

String textForLocale(String source, Locale locale) {
  final translated = _catalog[source]?[_languageIndex(locale)];
  return translated?.isNotEmpty == true ? translated! : source;
}

String _toTraditional(String source) {
  var value = source;
  const phrases = <String, String>{
    '账号': '帳號',
    '卡片': '卡片',
    '设置': '設定',
    '信息': '資訊',
    '资料': '資料',
    '费用': '費用',
    '地区': '地區',
    '发现': '發現',
    '显示': '顯示',
    '网络': '網路',
    '保存': '儲存',
    '浏览': '瀏覽',
    '记录': '記錄',
    '删除': '刪除',
    '确认': '確認',
    '开启': '開啟',
    '关闭': '關閉',
    '应用': '應用程式',
    '语言': '語言',
    '选择': '選擇',
    '添加': '新增',
    '当前': '目前',
    '暂无': '暫無',
    '还没有': '尚未',
    '加载': '載入',
    '推荐': '推薦',
    '变更': '變更',
    '规则': '規則',
    '订阅': '訂閱',
    '会员': '會員',
    '同步': '同步',
    '帮助': '說明',
    '关于': '關於',
    '反馈': '回饋',
    '联系': '聯絡',
  };
  for (final entry in phrases.entries) {
    value = value.replaceAll(entry.key, entry.value);
  }
  return value;
}
